import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class AccountsService {
  private accounts = {
    "middleName": "D",
    "resetPassword": false,
    "isenrolmentVerified": false,
    "userType": "",
    "enabled": false,
    "alertsEnabled": false,
    "ficoEnrolled": false,
    "migrationComplete": false,
    "estatementEnroll": false,
    "estatementNotify": false,
    "appRatingEnabled": true,
    "firstName": "LAKYN",
    "lastName": "ROGERS",
    "email": "ROGERLAK000@GMAIL.COM",
    "mobile": "5093859057",
    "isSMSBankingEnabled": true,
    "isAlertEnabled": true,
    "failedLoginCount": 0,
    "failedMfaCount": 0,
    "isLocked": false,
    "isMigrationComplete": false,
    "isEnabled": false,
    "isAccountUnMasked": true,
    "userName": "machugas",
    "uniqueIdentifier": "VXVqUHdpa0x6VHBtMDN4ZTBodGZ4UT09",
    "AccessDeviceObject": [
        {
            "platform": "WEB",
            "deviceId": "12984098796017c66ea1a99589999495",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
            "preAuthToken": "ILQwwqwSXlXfIVGJ",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "19147786846017f9badea87543726733",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
            "preAuthToken": "onoODhWeUjTjqcpo",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "3287914386021017a952fa738328562",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "hkUOhblwQmBpTTMJ",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "IOS",
            "pushNotificationToken": "94B813F425F0ED9D02DFF2F94689940D2CF94ADC099A44F19B50BDC9F1B83499",
            "deviceId": "9B0A47B0-09F9-405E-9356-497D8326932F",
            "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
            "preAuthToken": "UUbBeUKfwmsqvagt",
            "os": "iOS",
            "osVersion": "14.0",
            "deviceName": "iPhone",
            "screenDimension": "375x812",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "17396586076006968e3dc63202036370",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
            "preAuthToken": "InIVnysOdbjYKuwk",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "4695266206000c15386167353269354",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
            "preAuthToken": "CXJoIMxdEiRWCHJk",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "2073171455601a2287b94fe546765978",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
            "preAuthToken": "TkKzBHajsBaPsrYK",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "1201680894601afbffa22db781211879",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
            "preAuthToken": "NokmkBRuMhqCfGrk",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "21242916926017c2435aea2963983702",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
            "preAuthToken": "BNpNOHZhyvsoiuSy",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "c0-Z4isFRhiDVMPa_527Gm:APA91bGu0kFDGDgIhM4IHRWOfCMAmta76S2d3ldM5XpZBoQLODbT8qJff_-EudvGlAkEIZjeZgRrX1zhYr_6chdngKozBMldKReMaQuem0VLEwsQy72c-wErb_7enspB3buklhlSeE6T",
            "deviceId": "86adcc21d80adf92",
            "userAgent": "Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86 Build/RPB2.200611.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.81 Mobile Safari/537.36",
            "preAuthToken": "mnlLaJbsNxaLDVUp",
            "os": "Android",
            "osVersion": "11",
            "deviceName": "Google-google-sdk_gphone_x86",
            "screenDimension": "2088x1080",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "4072528626012e3af46227745876281",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
            "preAuthToken": "MQLHhOUshVSgZZCW",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "IOS",
            "pushNotificationToken": "6904D6E8F6D2740C27800258D77DCA9B96D66C1DCE488D2C49E2CCFBD7DFBB9B",
            "deviceId": "188CBC2C-11A0-4FCC-9620-36741FA4E25F",
            "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
            "preAuthToken": "oOgzuwwICYWYNJIR",
            "os": "iOS",
            "osVersion": "14.2",
            "deviceName": "iPhone",
            "screenDimension": "375x667",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "2120611217602b95e3a3a44327742647",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "kwRFmfmsYBiTRsin",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "1220688090602e4bd845be5662487784",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
            "preAuthToken": "MCZjluzZeZdDEbre",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "47844307560333e7e1d5af535040374",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
            "preAuthToken": "UvfQTcCTJubEDuUP",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "201193229160347e14be92f553683912",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
            "preAuthToken": "CrLoKFbHuBFEsgBV",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "13783943655fe98953ea62f773477110",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "dElBLhbWQivRWVTi",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "1007996955601a506f0630c694286220",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
            "preAuthToken": "bwoPYLuwjYVKGPeK",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "fAxCyQdyRn6GcATqSyYA-b:APA91bEQVN6eUMeYANxZE98zXJEZBWXlZwpNkFr0PpVhgcXMXjrtxxEE_kfAqsCxKBthZ1HCYQg_SbWg2_nNiwGSYTSaye4-n5yB0R6XscElNOQJfyTTOUho71ZXR7VsuQUwDkrboMTH",
            "deviceId": "73473e47192ecf5c",
            "userAgent": "Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.190920.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36",
            "preAuthToken": "FaokczuwJeDURIRM",
            "os": "Android",
            "osVersion": "10",
            "deviceName": "Google-google-Android SDK built for x86",
            "screenDimension": "2088x1080",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "dgtXbDgUSFqmj73Tm1Y11E:APA91bF5yd1qx6jpLs6QtBySwZHy-8h1N9NSILjRPc6e9O61980A3QXLLqyRZuhAUI0TuSNBnqCBNz86YThzlBwtqKzSdw_Ud4riCNM83m6z-SuTLrBVh0wa3R1_kg3Kb5mfRFI6oPVd",
            "deviceId": "308f82e0ff9dbd24",
            "userAgent": "Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86_arm Build/RPB3.200720.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36",
            "preAuthToken": "pVOrPcTbujeWykPa",
            "os": "Android",
            "osVersion": "11",
            "deviceName": "Google-google-sdk_gphone_x86_arm",
            "screenDimension": "2792x1440",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": true
        },
        {
            "platform": "WEB",
            "deviceId": "193839815360349b804ce60108019856",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "HBMrARobVdesiJXm",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "dM-eLaqfSN2Js-ShPVj6L8:APA91bHZEYOYLTwGzrplAYxgyQ2yhjck849TvJSud4x8m1fDnRv08jTpJWRXl6HxfX0KL357zAb5ERziTMpcM1vsBzL3r9vPSs33vSMh0i54BKXk7daudUBBx8QYZwQIjiC4D-ggqbCH",
            "deviceId": "00706e6ffb739abb",
            "userAgent": "Mozilla/5.0 (Linux; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.035; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36",
            "preAuthToken": "zPqhKJRlbnrNLitC",
            "os": "Android",
            "osVersion": "8.1.0",
            "deviceName": "Google-google-Android SDK built for x86",
            "screenDimension": "1794x1080",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "2785491226034c79c6349a372155746",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15",
            "preAuthToken": "MBjSoHvMDWBlfziH",
            "os": "OS X",
            "osVersion": "10_15_6",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "17224895860153a98e1844274152372",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "kubOhTzHHiksugkz",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "emMFfJllS1GzMRUUlw7Uwy:APA91bFvYGDuQCiJTwoYgFB9KSxw77VVt_0AlUx9aiFbfsBwmE5_aMkA_QhV9ZD69SvWOkCyoC7-yAt25RDTYc6MYD5zUexphg19Tb41mn_SMIgSOsE7ltzKsWpENCQDDFsM7o14ryk8",
            "deviceId": "e211c32d89c1b9ad",
            "userAgent": "Mozilla/5.0 (Linux; Android 9; COR-AL00 Build/HUAWEICOR-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.181 Mobile Safari/537.36",
            "preAuthToken": "mtKmNUEvGOTfusHU",
            "os": "Android",
            "osVersion": "9",
            "deviceName": "HUAWEI-HONOR-COR-AL00",
            "screenDimension": "2128x1080",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "46831696860198422ae1d2121030897",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
            "preAuthToken": "wYgOldQGVoimKpKC",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "2108925740603485b19dc89102333880",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
            "preAuthToken": "TOmhLkJmnXlTnvav",
            "os": "OS X",
            "osVersion": "10_15_5",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "99884820960261b2f0a2a1364106656",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "prpPorsytAFqNlcF",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "6227620465ffe79dbb47e8443276829",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "rQOErNaEXzVIvaqn",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "16174036216022019b163f0442852712",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
            "preAuthToken": "xzkgKprXkxXRfZCM",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "dUSETnrrTB-CHY_sx1rpmp:APA91bGx68DU0cA-PwB9npgbLyLhJKw8PN7TpCk52rdljN2HSy0A_bsn0E4g4SPv1HTC16DiigF6dbKR8iFXhJiV5oePbBw6oyxWTm2WZz8DyQTJQcEPk01VDVJYPOhXkpgnDcLaakiF",
            "deviceId": "7c0df821855b2464",
            "userAgent": "Mozilla/5.0 (Linux; Android 10; RMX1921 Build/QKQ1.190918.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.141 Mobile Safari/537.36",
            "preAuthToken": "GCgZciqjjDonewyk",
            "os": "Android",
            "osVersion": "10",
            "deviceName": "realme-realme-RMX1921",
            "screenDimension": "2152x1080",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "DISABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "629083136602f813a8ce78835482086",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
            "preAuthToken": "dzMBxlDOmYHsvcct",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "75872560260125cab036b6336256992",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
            "preAuthToken": "GiVOTErJKjlSHXss",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "959287236601a0c8342d9c470165530",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "OCFmPUQmIrNvVMEn",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "2081233505601cdaee11324670577407",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
            "preAuthToken": "HeBagxWYBSnozFIr",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "eDb8iJxVS5yuqJN06xndJK:APA91bHxUji-liIf89WaeSsdpVgLK4ILz1LCXgCP1mjz53qXhxRowruqMshrjfB9Fzm17QMIUpJL2r2B7_AzC57PdVRRz95h6fyA2am8wM6AHs9zU4yFjFSAT4DW-tNAixvGkBmCXVI6",
            "deviceId": "69d25f0aec512518",
            "userAgent": "Mozilla/5.0 (Linux; Android 10; HD1901 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.152 Mobile Safari/537.36",
            "preAuthToken": "VFOjKfVvnbTheBLZ",
            "os": "Android",
            "osVersion": "10",
            "deviceName": "OnePlus-OnePlus-HD1901",
            "screenDimension": "2332x1080",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "362480740602e97fdd7019484098375",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
            "preAuthToken": "AUJXFevauBgxrBQS",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "1299712357600a455acc312942947235",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "INAkhvskpKXFUPoV",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "ANDROID",
            "pushNotificationToken": "erXK9kB3QqaWftbTBvY8_w:APA91bElClzsIGChG6Yk1gN-9087rFmLJIcz5gKdbxTR19EhNWAoCvzsM7ohof7JC-REEt4YTawLD80KextHKlQl_EVdKywBvLNTIW67kq200-R89q3n1-eEuP78nz-gDYdWRCNtwKh5",
            "deviceId": "d1c251157fb51f76",
            "userAgent": "Mozilla/5.0 (Linux; Android 11; Mi A3 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.198 Mobile Safari/537.36",
            "preAuthToken": "CGPydlYxnvtontaM",
            "os": "Android",
            "osVersion": "11",
            "deviceName": "Xiaomi-Xiaomi-Mi A3",
            "screenDimension": "1425x720",
            "trusted": false,
            "deviceType": "PHONE",
            "status": "DISABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "1107407413603473e40fd5e522608907",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
            "preAuthToken": "gPMFTJAiixOUGSTk",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "1328256449601ee0c0d0bfe168137754",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
            "preAuthToken": "XiPgaADnIXHPONXF",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "537421308601a4d063a2c4164612707",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
            "preAuthToken": "RMQHQpZLEopqbMTV",
            "os": "Linux",
            "osVersion": "N/A",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "808608617601a75c770380547664738",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
            "preAuthToken": "VIzIgNBoBZnHzwSp",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        },
        {
            "platform": "WEB",
            "deviceId": "4932230516020d7d745675916101521",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
            "preAuthToken": "UqkQJbpmhIYWmMrS",
            "os": "Windows",
            "osVersion": "10.0",
            "deviceName": "N/A",
            "trusted": false,
            "deviceType": "COMPUTER",
            "status": "ENABLED",
            "updateLastUsed": false,
            "rooted": false
        }
    ],
    "isAlertsEnabled": false,
    "roles": [],
    "isP2PEnrolled": false,
    "isMrdcEnrolled": false,
    "isFicoEnrolled": false,
    "mobileCountryCode": "1",
    "lastLoginTime": "02/23/2021 03:55 AM",
    "isEstatementEnroll": false,
    "isEstatementNotify": false,
    "isPfmEnrolled": true,
    "tcModel": [],
    "Extension": [
        {
            "key": "BROWSER_PREV_LOGIN",
            "value": "1614074433512"
        },
        {
            "key": "VOICE_STATUS",
            "value": "ENABLED"
        },
        {
            "key": "MOBILE_APP_PREV_LOGIN",
            "value": "1614077749202"
        },
        {
            "key": "VOICE_PHONE_NUMBER_2",
            "value": "5093859057"
        },
        {
            "key": "BROWSER_LAST_ACTIVATION_DATE",
            "value": "1611681427642"
        },
        {
            "key": "VOICE_PHONE_NUMBER_3",
            "value": "5095357613"
        },
        {
            "key": "BROWSER_LAST_DEACTIVATION_DATE"
        },
        {
            "key": "MOBILE_APP_LAST_LOGIN",
            "value": "1614078498924"
        },
        {
            "key": "DEFAULT_OTP_CHANNEL",
            "value": "SMS"
        },
        {
            "key": "BROWSER_FIRST_LOGIN",
            "value": "1611681472065"
        },
        {
            "key": "ENROLLMENT_CHANNEL",
            "value": "BROWSER"
        },
        {
            "key": "ACTIVITY_SINCE_LAST_LOGIN",
            "value": "[{\"memberNumberToken\":\"enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09\",\"accountNumberToken\":\"ajluYlRNVkdjbzNLZElVMXAwcHZmUT09\",\"accountType\":\"Credit Card\"},{\"memberNumberToken\":\"enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09\",\"accountNumberToken\":\"R1oraVphMkxOZmo5UFV3ZEZEUE9EUT09\",\"accountType\":\"Checking\"}]"
        },
        {
            "key": "MOBILE_APP_FIRST_LOGIN",
            "value": "1611681428000"
        },
        {
            "key": "VOICE_PHONE_COUNTRY_CODE_1",
            "value": "1"
        },
        {
            "key": "VOICE_PHONE_COUNTRY_CODE_3",
            "value": "1"
        },
        {
            "key": "MOBILE_APP_STATUS",
            "value": "ENABLED"
        },
        {
            "key": "VOICE_PHONE_COUNTRY_CODE_2",
            "value": "1"
        },
        {
            "key": "DEFAULT_MFA_TYPE",
            "value": "OTP"
        },
        {
            "key": "BROWSER_LAST_LOGIN",
            "value": "1614074471210"
        },
        {
            "key": "BROWSER_STATUS",
            "value": "ENABLED"
        },
        {
            "key": "VOICE_PHONE_NUMBER_1",
            "value": "5093859057"
        }
    ],
    "isCommercial": false,
    "isOrganisation": false,
    "isOnlineAccessBlocked": false,
    "isAppRatingEnabled": true,
    "isBusinessUser": false,
    "Member": [
        {
            "estatementOption": 1,
            "estatementNotifyOption": 1,
            "firstName": "LAKYN",
            "middleName": "D",
            "lastName": "ROGERS",
            "primaryMemberName": "LAKYN D ROGERS ",
            "p2pUserName": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09",
            "p2pPassword": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09",
            "lastAddressVerified": 1533106800000,
            "p2PEnrolled": false,
            "billPayEnrolled": false,
            "enoticeEnrolled": false,
            "rdcenrolled": false,
            "memberNumberToken": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09",
            "maskedMemberNumber": "0000781531",
            "iDMember": 0,
            "isBillPayEligible": true,
            "isBillPayAvailable": false,
            "isBillPayEnrolled": false,
            "isP2PEnrolled": false,
            "isRDCEnrolled": false,
            "isEstatementEnrolled": true,
            "isEnoticeEnrolled": false,
            "isMrdcEligible": true,
            "ownerShipType": "Primary",
            "isPrimary": false,
            "isTransactionEnabled": true,
            "isFICOEnrollmed": true,
            "isCommercial": false,
            "isEstatementEnabled": true,
            "Account": [
                {
                    "productName": "RENTAL REPAIR",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.26",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "07/07/2014",
                    "lastDividendPaid": "0.05",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "781531009",
                    "accountNickName": "RENTAL REPAIR",
                    "maskedAccountNumber": "00",
                    "accountNumberToken": "L2pwVVlBNGx2ZHllZ05FanVSbkg3QT09",
                    "achNumber": "781531009",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "RENTAL REPAIR",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$1,262.48",
                    "principalBalance": "852.19",
                    "ledgerBalance": "$1,262.48",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "RENTAL REPAIR",
                    "accountNumber": "00",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "1262.48",
                    "availableBalanceUnFormat": "1262.48",
                    "colourCode": "LiverChestnut",
                    "iDAccount": 207400,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "TRIPS",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.15",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "08/09/2016",
                    "lastDividendPaid": "0.09",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "781531017",
                    "accountNickName": "TRIPS",
                    "maskedAccountNumber": "01",
                    "accountNumberToken": "V1NveWVxOEpoMWs4alR0RTJTWEJUZz09",
                    "achNumber": "781531017",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "TRIPS",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$2,150.18",
                    "principalBalance": "40.00",
                    "ledgerBalance": "$2,150.18",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "TRIPS",
                    "accountNumber": "01",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "2150.18",
                    "availableBalanceUnFormat": "2150.18",
                    "colourCode": "Sepia",
                    "iDAccount": 207401,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "DOGS",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.01",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "03/20/2017",
                    "lastDividendPaid": "0.01",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "781531025",
                    "accountNickName": "DOGS",
                    "maskedAccountNumber": "02",
                    "accountNumberToken": "bTJJMDA0YmlDdzMxQk56a0xXQ05pUT09",
                    "achNumber": "781531025",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "DOGS",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$146.01",
                    "principalBalance": "1000.00",
                    "ledgerBalance": "$146.01",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "DOGS",
                    "accountNumber": "02",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "146.01",
                    "availableBalanceUnFormat": "146.01",
                    "colourCode": "PastelOrange",
                    "iDAccount": 207402,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "MISC",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.02",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "08/29/2017",
                    "lastDividendPaid": "0.02",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "10078153100033",
                    "accountNickName": "MISC",
                    "maskedAccountNumber": "03",
                    "accountNumberToken": "Ly9qWi9qa2lyVHFSeW5hSUZrU1huQT09",
                    "achNumber": "10078153100033",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "MISC",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$0.48",
                    "principalBalance": "300.00",
                    "ledgerBalance": "$0.48",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "MISC",
                    "accountNumber": "03",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "0.48",
                    "availableBalanceUnFormat": "0.48",
                    "colourCode": "BlanchedAlmond",
                    "iDAccount": 207403,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "URIAH FUN MONEY",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.03",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "08/29/2017",
                    "lastDividendPaid": "0.01",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "10078153100041",
                    "accountNickName": "URIAH FUN MONEY",
                    "maskedAccountNumber": "04",
                    "accountNumberToken": "bXVZOExjY3pySUY0aE9HRm1BcGdTQT09",
                    "achNumber": "10078153100041",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "URIAH FUN MONEY",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$183.47",
                    "principalBalance": "25.00",
                    "ledgerBalance": "$183.47",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "URIAH FUN MONEY",
                    "accountNumber": "04",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "183.47",
                    "availableBalanceUnFormat": "183.47",
                    "colourCode": "ElectricViolet",
                    "iDAccount": 207404,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "BONUS SAVER SAVINGS",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "24.94",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "08/29/2017",
                    "lastDividendPaid": "3.67",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "32",
                    "micrNumber": "10078153100058",
                    "accountNickName": "BONUS SAVER SAVINGS",
                    "maskedAccountNumber": "05",
                    "accountNumberToken": "QXpIL1dXVEpkaUVjU2pISkVRZmhrQT09",
                    "achNumber": "10078153100058",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "BONUS SAVER SAVINGS",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$5,465.91",
                    "principalBalance": "25.00",
                    "ledgerBalance": "$5,465.91",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "BONUS SAVER SAVINGS",
                    "accountNumber": "05",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "5465.91",
                    "availableBalanceUnFormat": "5465.91",
                    "colourCode": "Irresistible",
                    "iDAccount": 207405,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "EATING OUT",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.00",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "08/29/2017",
                    "lastDividendPaid": "0.01",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "10078153100066",
                    "accountNickName": "EATING OUT",
                    "maskedAccountNumber": "06",
                    "accountNumberToken": "MWRka0wwazhBQ0o1SkxRYmNrMmFIUT09",
                    "achNumber": "10078153100066",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "EATING OUT",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$1.97",
                    "principalBalance": "50.00",
                    "ledgerBalance": "$1.97",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "EATING OUT",
                    "accountNumber": "06",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "1.97",
                    "availableBalanceUnFormat": "1.97",
                    "colourCode": "SpiroDiscoBall",
                    "iDAccount": 207406,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "HOLIDAY&BIRTHDAY",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.16",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "07/06/2018",
                    "lastDividendPaid": "0.02",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "10078153100074",
                    "accountNickName": "HOLIDAY&BIRTHDAY",
                    "maskedAccountNumber": "07",
                    "accountNumberToken": "dXFBL1FwbEo4NnFxOEhRMCtXTUFLUT09",
                    "achNumber": "10078153100074",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "HOLIDAY&BIRTHDAY",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$552.85",
                    "principalBalance": "20.00",
                    "ledgerBalance": "$552.85",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "HOLIDAY&BIRTHDAY",
                    "accountNumber": "07",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "552.85",
                    "availableBalanceUnFormat": "552.85",
                    "colourCode": "Glaucous",
                    "iDAccount": 207407,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "LAKYN FUN MONEY",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.06",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "09/02/2019",
                    "lastDividendPaid": "0.03",
                    "ofxAccountGroup": "Savings",
                    "pfmAccountGroup": "savings",
                    "certificateTermType": "0",
                    "accountCode": "0",
                    "micrNumber": "10078153100082",
                    "accountNickName": "LAKYN FUN MONEY",
                    "maskedAccountNumber": "08",
                    "accountNumberToken": "d1QwMHFmbmx5OGMwZlAxMFUvS01EQT09",
                    "achNumber": "10078153100082",
                    "accountTypeAcronym": "SAV",
                    "accountType": "Savings",
                    "accountTitle": "LAKYN FUN MONEY",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$366.25",
                    "principalBalance": "50.00",
                    "ledgerBalance": "$366.25",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "LAKYN FUN MONEY",
                    "accountNumber": "08",
                    "accountGroup": "Savings",
                    "ledgerBalanceUnFormat": "366.25",
                    "availableBalanceUnFormat": "366.25",
                    "colourCode": "NeonFuchsia",
                    "iDAccount": 207408,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "BONUS CHECKING",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "4.28",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "07/07/2014",
                    "lastDividendPaid": "0.38",
                    "ofxAccountGroup": "Checking",
                    "pfmAccountGroup": "checking",
                    "certificateTermType": "0",
                    "accountCode": "8",
                    "micrNumber": "781531108",
                    "accountNickName": "BONUS 1234",
                    "maskedAccountNumber": "10",
                    "accountNumberToken": "R1oraVphMkxOZmo5UFV3ZEZEUE9EUT09",
                    "achNumber": "781531108",
                    "accountTypeAcronym": "CHK",
                    "accountType": "Checking",
                    "accountTitle": "BONUS 1234",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$81.13",
                    "principalBalance": "300.00",
                    "ledgerBalance": "$81.13",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": true,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "BONUS CHECKING",
                    "accountNumber": "10",
                    "accountGroup": "Checking",
                    "ledgerBalanceUnFormat": "81.13",
                    "availableBalanceUnFormat": "81.13",
                    "colourCode": "Brass",
                    "iDAccount": 207409,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": true,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "CourtesyPay": {
                        "enabledForCourtesyPay": true
                    },
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "BILLS",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.00",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "09/22/2014",
                    "lastDividendPaid": "0.00",
                    "ofxAccountGroup": "Checking",
                    "pfmAccountGroup": "checking",
                    "certificateTermType": "0",
                    "accountCode": "14",
                    "micrNumber": "781531116",
                    "accountNickName": "BILLS",
                    "maskedAccountNumber": "11",
                    "accountNumberToken": "aHQveXJKcHgxYTZVbTRqVHpsYzdNZz09",
                    "achNumber": "781531116",
                    "accountTypeAcronym": "CHK",
                    "accountType": "Checking",
                    "accountTitle": "BILLS",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$2,696.04",
                    "principalBalance": "75.00",
                    "ledgerBalance": "$2,696.04",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "BILLS",
                    "accountNumber": "11",
                    "accountGroup": "Checking",
                    "ledgerBalanceUnFormat": "2696.04",
                    "availableBalanceUnFormat": "2696.04",
                    "colourCode": "Stizza",
                    "iDAccount": 207410,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": true,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "CourtesyPay": {
                        "enabledForCourtesyPay": true
                    },
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "RENTAL",
                    "dividendYTD": "0.00",
                    "currentInterestRate": "0.000",
                    "dividendPYTD": "0.00",
                    "minimumDepositAmount": "0.00",
                    "regdCount": "N/A",
                    "certificateTerm": "0",
                    "certificateRate": "0.000",
                    "openDate": "06/08/2018",
                    "lastDividendPaid": "0.00",
                    "ofxAccountGroup": "Checking",
                    "pfmAccountGroup": "checking",
                    "certificateTermType": "0",
                    "accountCode": "14",
                    "micrNumber": "10078153100124",
                    "accountNickName": "RENTAL",
                    "maskedAccountNumber": "12",
                    "accountNumberToken": "dndOMHIxUG9zWjdUREtMbHFuWmF0UT09",
                    "achNumber": "10078153100124",
                    "accountTypeAcronym": "CHK",
                    "accountType": "Checking",
                    "accountTitle": "RENTAL",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$1,509.70",
                    "principalBalance": "3300.00",
                    "ledgerBalance": "$1,509.70",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": true,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "RENTAL",
                    "accountNumber": "12",
                    "accountGroup": "Checking",
                    "ledgerBalanceUnFormat": "1509.70",
                    "availableBalanceUnFormat": "1509.70",
                    "colourCode": "SafetyYellow",
                    "iDAccount": 207411,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "0.000",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": true,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": true,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "CourtesyPay": {
                        "enabledForCourtesyPay": true
                    },
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "2014 FORD EXPLORER-V6",
                    "interestYTD": "191.06",
                    "interestPYTD": "47.32",
                    "ofxAccountGroup": "CdtLine",
                    "pfmAccountGroup": "loan",
                    "statementBalance": "0.00",
                    "paymentDue": "255.00",
                    "statementDate": "08/31/2020",
                    "accountCode": "0",
                    "micrNumber": "20078153100033",
                    "accountNickName": "2014 FORD EXPLORER-V6",
                    "maskedAccountNumber": "03",
                    "accountNumberToken": "Ly9qWi9qa2lyVHFSeW5hSUZrU1huQT09",
                    "achNumber": "20078153100033",
                    "accountTypeAcronym": "LOAN",
                    "accountType": "Closed End",
                    "accountTitle": "2014 FORD EXPLORER-V6",
                    "accountCategoryCode": "0-LOAN",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$0.00",
                    "ledgerBalance": "$16,524.93",
                    "payOffAmount": "255.00",
                    "nextDueDate": "04/30/2021",
                    "totalPayOffAmount": "16537.33",
                    "isFundTransferSource": false,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": false,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "2014 FORD EXPLORER-V6",
                    "accountNumber": "03",
                    "creditLimit": "0.00",
                    "accountGroup": "Loan",
                    "ledgerBalanceUnFormat": "16524.93",
                    "availableBalanceUnFormat": "0.00",
                    "colourCode": "Redwood",
                    "iDAccount": 207412,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "2.490",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": false,
                    "isDelinquent": false,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                },
                {
                    "productName": "VISA PLATINUM",
                    "interestYTD": "0.00",
                    "interestPYTD": "201.56",
                    "externalLoanID": "498863XXXXXXXXXX",
                    "ofxAccountGroup": "CDT",
                    "pfmAccountGroup": "cards",
                    "statementBalance": "285.55",
                    "paymentDue": "25.00",
                    "statementDate": "08/31/2020",
                    "accountCode": "95",
                    "micrNumber": "781531900",
                    "accountNickName": "VISA PLATINUM",
                    "maskedAccountNumber": "90",
                    "accountNumberToken": "ajluYlRNVkdjbzNLZElVMXAwcHZmUT09",
                    "achNumber": "781531900",
                    "accountTypeAcronym": "LOAN",
                    "accountType": "Credit Card",
                    "accountTitle": "VISA PLATINUM",
                    "accountCategoryCode": "3-LOAN",
                    "currency": "USD",
                    "accountStatus": "Active",
                    "availableBalance": "$6,822.80",
                    "ledgerBalance": "$677.20",
                    "payOffAmount": "100.00",
                    "nextDueDate": "10/28/2020",
                    "totalPayOffAmount": "777.20",
                    "isFundTransferSource": true,
                    "isFundTransferDestination": true,
                    "isHistoryAvailable": true,
                    "isBillPayEligible": true,
                    "isMrdcEligible": false,
                    "isP2pEligible": false,
                    "isShowAvailBalance": true,
                    "isShowLedgerBalance": true,
                    "isPriority": true,
                    "isEnabled": true,
                    "isSwipeBalEnabled": false,
                    "accountName": "VISA PLATINUM",
                    "accountNumber": "90",
                    "creditLimit": "7500.00",
                    "accountGroup": "CreditCard",
                    "ledgerBalanceUnFormat": "677.20",
                    "availableBalanceUnFormat": "6822.80",
                    "colourCode": "DeepChampagne",
                    "iDAccount": 207413,
                    "isBillingAccount": false,
                    "isPersonalLoan": false,
                    "isAutoLoan": false,
                    "isOverDraft": false,
                    "isFirstMortgage": false,
                    "AccountSetting": [],
                    "interestRate": "8.990",
                    "historyRule": "NON_PAGINATED",
                    "isRewardChecking": false,
                    "isStudentChecking": false,
                    "isVoiceEnabled": false,
                    "isSrtAvailable": true,
                    "isMortgageAccount": false,
                    "allowTitleUpdate": false,
                    "isDelinquent": true,
                    "isRewardPointAvailable": false,
                    "isPrimarySavingsAccount": false,
                    "isCourtesyPayEnabled": false,
                    "isPrincipalPayEnabled": false,
                    "isSkipPayEnabled": false,
                    "isIRAAccountType": false,
                    "isESAAccountType": false,
                    "isExternalLoanPaymentEnabled": false,
                    "isExportOptionAvailable": true
                }
            ],
            "CardDetail": [
                {
                    "cardNumberToken": "NW9ocVhCWjludG9FSUJ0RzdoUy9Bc1J2aDh3UjlhZkRJZlFkNXd6RUdIRT0=",
                    "cardHolderName": "LAKYN D ROGERS ",
                    "cardType": "VISA DEBIT CARD",
                    "maskedCardNumber": "xxxx-xxxx-xxxx-5236",
                    "cardStatus": true,
                    "isFrozen": false,
                    "isRewardsEnabled": false,
                    "CardAccess": [
                        {
                            "idType": "0",
                            "accountNumberToken": "R1oraVphMkxOZmo5UFV3ZEZEUE9EUT09",
                            "memberNumberToken": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09"
                        }
                    ]
                },
                {
                    "cardNumberToken": "cklvRjVpbmg3MUFTbU51bDBONFdjWDViZ3dsMU5rTE5yUHV3K01qYU5WTT0=",
                    "cardHolderName": "LAKYN D ROGERS ",
                    "cardType": "VISA PLATINUM",
                    "maskedCardNumber": "xxxx-xxxx-xxxx-4239",
                    "cardStatus": true,
                    "isFrozen": false,
                    "isRewardsEnabled": false,
                    "CardAccess": [
                        {
                            "idType": "1",
                            "accountNumberToken": "ajluYlRNVkdjbzNLZElVMXAwcHZmUT09",
                            "memberNumberToken": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09"
                        }
                    ]
                }
            ],
            "FicoScores": {
                "totalElements": 0,
                "totalPages": 0,
                "numberOfElements": 0,
                "FicoScore": [
                    {
                        "rowID": 0,
                        "isSuccess": false
                    }
                ]
            },
            "Address": {
                "uspsVerified": false,
                "addressVerification": 0,
                "street1": "10414 N HUMBOLDT DR",
                "zipcode": "99218-1519",
                "city": "SPOKANE",
                "state": "WA",
                "isInternational": false,
                "isPrimary": true
            },
            "RoundUpToSavings": {
                "fromMemberNumberToken": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09",
                "fromAccountNumberToken": "aHQveXJKcHgxYTZVbTRqVHpsYzdNZz09",
                "toAccountNumberToken": "V1NveWVxOEpoMWs4alR0RTJTWEJUZz09",
                "enabledForRoundUptoSaving": true,
                "roundUpValue": "1"
            },
            "billpayToken": "enI4bGV4Y1VHWmRldDYyV2E0TlVBQT09",
            "isAddressChangeRequired": false,
            "isPhoneUpdateRequired": false,
            "isEmailUpdateRequired": false
        }
    ],
    "Alert": [],
    "CrossMembers": [],
    "CrossMember": [],
    "isAdmin": false
}

  constructor() { }
  maskedMemberNo = this.accounts.Member[0].maskedMemberNumber;
  getStructuredAccount(accounts) {
    return accounts.map((account) => {
      return  {
               id: account.iDAccount,
               title: account.productName,
               maskedMemberNumber: this.maskedMemberNo,
               maskedAccountNumber: account.maskedAccountNumber,
               availableBalance: account.availableBalance,
               accountType: account.accountType
              }
    })
  }


  getCheckingAccounts() {
   const checkingAccounts = this.accounts.Member[0].Account.filter((account) => {
      return account.accountType === 'Checking';
    })

    return this.getStructuredAccount(checkingAccounts);
  }

  getSavingsAccount() {
    const savingsAccounts =  this.accounts.Member[0].Account.filter((account) => {
      return account.accountType === 'Savings';
    })

    return this.getStructuredAccount(savingsAccounts);
  }

  getCreditCardAccount() {
    const creditCardAccounts = this.accounts.Member[0].Account.filter((account) => {
      return account.accountType === 'Credit Card';
    })

    return this.getStructuredAccount(creditCardAccounts);
  }

  getLoanAccounts() {
    const loadAccounts =  this.accounts.Member[0].Account.filter((account) => {
      return account.accountType === 'Closed End';
    })

    return this.getStructuredAccount(loadAccounts);
  }

  getAccountDetail(id) {
    return this.accounts.Member[0].Account.find(account => {
      return account.iDAccount === Number(id);
    })
  }
}
